[package]
name = "rscrypt"
description = "rscrypt is a simple, fast, and secure encryption tool written in Rust."
version = "0.1.6"
edition = "2021"
authors = ["Achaq <contact@achaq.codes>"]
license = "MIT"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.2"
regex = "1.6.0"

